services:
  mycoria-a:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/mycoria/mycoria-node-a.yaml:/etc/mycoria/config.yaml
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8081:8081"
    environment:
      - EXPOSE_SERVICE=nginx-matsutake
      - EXPOSE_SERVICE_PORT=80
      - EXPOSE_PORT=8080
      - EXPOSE_REMOTE_HOST=fd1a:9c70:1537:fce:cbc4:bb57:ac9b:50e5
      - EXPOSE_REMOTE_PORT=8081
    networks:
      - node-a
      - peering

  mycoria-b:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/mycoria/mycoria-node-b.yaml:/etc/mycoria/config.yaml
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8082:8082" 
    environment:
      - EXPOSE_SERVICE=nginx-truffle
      - EXPOSE_SERVICE_PORT=80
      - EXPOSE_PORT=8080
      - EXPOSE_REMOTE_HOST=fd1a:8fd0:d01e:8d3b:ce17:dc5b:83f:1d5
      - EXPOSE_REMOTE_PORT=8082
    networks:
      - node-b
      - peering

  nginx-matsutake:
    image: nginx:alpine
    volumes:
      - ./config/nginx/nginx-matsutake.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/matsutake.txt:/usr/share/nginx/html/matsutake.txt
    restart: unless-stopped
    networks:
      - node-a

  nginx-truffle:
    image: nginx:alpine
    volumes:
      - ./config/nginx/nginx-truffle.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/truffle.txt:/usr/share/nginx/html/truffle.txt
    networks:
      - node-b

networks:
  node-a:
  node-b:
  peering: